version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
  main:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: app.Dockerfile
    restart: always
    container_name: main
    ports:
      - "9090:9090"
    environment:
      - HTTP_PORT=${PORT}
      - PG_URL=${POSTGRES_URL}
      - PG_HOST=${POSTGRES_HOST}
      - PG_PORT=${POSTGRES_PORT}
      
volumes:
  db_data: